/* assets/config/theme.yml v1.0.0_202510250840 */
# ⭐️ _data/theme.yml의 공개용 미러입니다.
# ⭐️ Admin JS가 이 파일을 fetch합니다. _data/theme.yml 수정 시 여기도 꼭 덮어쓰세요.

brand: "GOFUNWITH – Explore. Create. Share."
domain: "blog.gofunwith.com"
url: "https://gosungjinmoon.github.io"
repo: "gosungjinmoon/gosungjinmoon.github.io"
github: "https://github.com/gosungjinmoon"
timezone: "Asia/Seoul"

# Google Analytics & Cloudflare
ga4_measurement_id: "G-R7N7G7QPBF"
cloudflare_beacon_token: "c7db8999eee4466bab1893a2361aed10"

# Admin Console & API Endpoints
cloudflare_worker_endpoint: "https://gfw-oauth-exchange.eric-moon.workers.dev"
n8n_webhook_subscribe: "https://n8n.gofunwith.com/webhook/subscribe"
github_oauth_client_id: "Ov23liqsljSBAqajz2eu"
