# GOFUNWITH Blog (Chirpy CI Fixed) 2025-10-30 14:08

title: "GOFUNWITH"
tagline: "Explore. Create. Share."
description: "기술, DIY, 캠핑, 생활자동화를 함께 즐기는 블로그"
url: "https://blog.gofunwith.com"
baseurl: ""

theme: jekyll-theme-chirpy
lang: ko
timezone: Asia/Seoul
paginate: 10
paginate_path: /page:num/

social:
  github: gosungjinmoon
  email: contact@gofunwith.com
  rss: true

google_analytics:
  id: G-R7N7G7QPBF

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - tmp
  - .github

markdown: kramdown
highlighter: rouge

languages: ["ko", "en"]
