/* _data/config.yml  v202510221600 */
nav:
  - label: Home
    href: "{{ '/ko/' | relative_url }}"
  - label: EN
    href: "{{ '/en/' | relative_url }}"
  - label: Tags
    href: "{{ '/ko/tags/' | relative_url }}"
social:
  github: "https://github.com/gosungjinmoon"
