/* _data/config.yml v1.0.0_202510250840 */
# 사이트 UI 및 네비게이션 설정
nav:
  - name:
      ko: "소개"
      en: "About"
    url: "/about/" # (페이지 생성 필요)
  - name:
      ko: "태그"
      en: "Tags"
    url: "/tags/"
  - name:
      ko: "검색"
      en: "Search"
    url: "/search/"

footer_links:
  - name: "Admin"
    url: "/admin/"
  - name: "GitHub"
    url: "https://github.com/gosungjinmoon" # theme.yml의 github 값으로 대체 가능
