/* _data/tags.yml v1.0.0_202510221638 */

# 태그의 메타데이터를 정의합니다.
# 태그 클라우드 표시 이름이나 설명을 추가할 수 있습니다.
# key: 태그 slug (포스트 front matter에 사용)
# name: 태그 페이지에 표시될 이름

tech:
  name: "Tech"
diy:
  name: "DIY"
camping:
  name: "Camping"
automation:
  name: "Automation"
experiment:
  name: "Experiment"
n8n:
  name: "n8n"
jekyll:
  name: "Jekyll"
